version: '3'

tasks:
  run:
    cmds:
      - uv run main.py

  build:
    cmds:
      - cd frontend && bun install && bun run build

  dev:
    cmds:
      - uv run main.py &
      - cd frontend && bun install && bun run dev

  make:
    cmds:
      - uv run task build
      - pyinstaller ./main.py --add-data "./frontend:./frontend" --onefile --distpath ./dist --name app
