version: '3'

tasks:
  run:
    cmds:
      - uv run task build
      - uv run main.py

  build:
    cmds:
      - cd frontend && bun install && bun run build

  dev:
    cmds:
      - uv run uvicorn main:app --reload & (cd frontend && bun install && bun run dev)

  make:
    cmds:
      - uv run task build
      - nuitka ./main.py --standalone --include-data-dir=./frontend/build/client=./frontend/build/client
